### ISSUE TITLE
Is Windstitches aware of conflicting tailwind classnames?

### ISSUE THREAD

**Issue by wmonecke** [vinpac/windstitch#19]
Would the following be possible?

```javascript
const craftInput = cva(
  [...],
  {
    variants: {
      size: {
        medium: ['text-base', 'h-11', 'px-3'],
      },
      iconLeading: {
        true: 'pl-10',
      },
    },
  },
);
```
This is a `cva` example but would migrate to WindStitches if it would work.

I am trying to create a `medium` input but when `iconLeading` is `true` I would like the padding to end up like this `pr-3 pl-10` which is the result of `px-3` + `pl-10`.

Would WindStitches be aware a `px-3` is applied and to override only the left part of the padding?

**Comment by vinpac** [comment]
You would need [tailwind-merge](https://www.npmjs.com/package/tailwind-merge) for that.
